# Generated by Django 5.1.2 on 2024-10-18 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_rolemodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='rol',
            new_name='role',
        ),
    ]
